#!/usr/bin/env python3
import argparse
from pathlib import Path


def _pick_tag(text: str) -> str:
    tag = "GLSL"
    while f"){tag}\"" in text:
        tag += "_"
    return tag


def main() -> int:
    parser = argparse.ArgumentParser(description="Wrap a GLSL file as a C++ raw string header.")
    parser.add_argument("--input", required=True, help="Path to the GLSL input file.")
    parser.add_argument("--output", required=True, help="Path to the output header file.")
    parser.add_argument("--var", required=True, help="C++ variable name for the shader string.")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    text = input_path.read_text(encoding="utf-8")
    if not text.endswith("\n"):
        text += "\n"

    tag = _pick_tag(text)

    output = []
    output.append("// Generated by gen_glsl_header.py. Do not edit.\n")
    output.append(f"static const char* {args.var} = R\"{tag}(\n")
    output.append(text)
    output.append(f"){tag}\";\n")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(output), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
