param(
    [string]$OutputDir = (Join-Path $PSScriptRoot "tmp")
)

$ErrorActionPreference = "Stop"

function Resolve-Tool([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK "Bin\$Name.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    $scoopCandidate = Join-Path $env:USERPROFILE "scoop\apps\vulkan\current\Bin\$Name.exe"
    if (Test-Path $scoopCandidate) {
        return $scoopCandidate
    }
    throw "$Name was not found on PATH, VULKAN_SDK, or the Scoop Vulkan SDK install path"
}

function Write-SpvInclude([string]$Path, [string]$Prefix, [array]$Variants) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// Generated by generate_vulkan_picture_shaders.ps1")
    $lines.Add("")
    for ($i = 0; $i -lt $Variants.Count; ++$i) {
        $bytes = [System.IO.File]::ReadAllBytes($Variants[$i])
        $lines.Add("static const unsigned int $($Prefix)$i[$($bytes.Length / 4)] = {")
        $words = New-Object System.Collections.Generic.List[string]
        for ($j = 0; $j -lt $bytes.Length; $j += 4) {
            $word = [BitConverter]::ToUInt32($bytes, $j)
            $words.Add(("0x{0:x8}u" -f $word))
        }
        for ($j = 0; $j -lt $words.Count; $j += 8) {
            $take = [Math]::Min(8, $words.Count - $j)
            $lines.Add("    " + (($words.GetRange($j, $take)) -join ", ") + ",")
        }
        $lines.Add("};")
        $lines.Add("")
    }
    $lines.Add("static const unsigned int *${Prefix}_code[$($Variants.Count)] = {")
    $lines.Add("    " + ((0..($Variants.Count - 1) | ForEach-Object { "$Prefix$_" }) -join ", "))
    $lines.Add("};")
    $lines.Add("static const int ${Prefix}_size[$($Variants.Count)] = {")
    $lines.Add("    " + (($Variants | ForEach-Object { [System.IO.File]::ReadAllBytes($_).Length }) -join ", "))
    $lines.Add("};")
    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding ASCII
}

$glslang = Resolve-Tool "glslangValidator"
$spirvVal = Resolve-Tool "spirv-val"

New-Item -ItemType Directory -Force $OutputDir | Out-Null
$workDir = Join-Path $OutputDir "vulkan_picture_spirv_work"
New-Item -ItemType Directory -Force $workDir | Out-Null

$vsSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

struct DisplayEye { mat4x4 mMatrix_CamPrj; };
layout (std140, row_major, binding=4) uniform DisplayState
{
    DisplayEye mEye[2];
    vec2       mResolution;
} display;

layout(location=0) in vec3 in_position;
layout(location=1) in vec3 in_normal;
layout(location=0) out vec3 out_direction;

// 0 = normal projected depth, 1 = reverse-Z far backdrop, 2 = less/equal far backdrop.
layout(constant_id = 0) const uint hostDepthBackdropMode = 0u;

void main()
{
    vec3 viewer_position = (layer.mLayerToViewer * vec4(in_position, 1.0)).xyz;
    out_direction = normalize(in_position);
    gl_Position = display.mEye[0].mMatrix_CamPrj * vec4(viewer_position, 1.0);
    if (hostDepthBackdropMode == 1u)
    {
        gl_Position.z = 0.0;
    }
    else if (hostDepthBackdropMode == 2u)
    {
        gl_Position.z = gl_Position.w;
    }
}
'@

$fsSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

layout(binding = 0) uniform sampler2D pictureTexture;
layout(location=0) in vec3 in_direction;
layout(location=0) out vec4 out_color;

const float k_pi = 3.1415927;

void main()
{
    vec3 nor = normalize(in_direction);
    vec2 uv = vec2(0.5 + 0.5 * atan(nor.x, -nor.z) / k_pi, acos(clamp(nor.y, -1.0, 1.0)) / k_pi);
    vec4 texel = texture(pictureTexture, uv);
#if COLOR_SPACE == 0
    vec3 color = pow(texel.rgb, vec3(2.2));
#else
    vec3 color = texel.rgb;
#endif
    float alpha = texel.a * layer.mOpacity;
    out_color = vec4(color, alpha);
}
'@

$vsPath = Join-Path $workDir "shader_pip360Equirect_vk.vert"
$fsPath = Join-Path $workDir "shader_pip360Equirect_vk.frag"
Set-Content -Path $vsPath -Value $vsSource -NoNewline -Encoding ASCII
Set-Content -Path $fsPath -Value $fsSource -NoNewline -Encoding ASCII

$vs2DSource = @'
#version 460

layout(location=0) out vec2 out_uv;

void main()
{
    vec2 positions[6] = vec2[](
        vec2(-1.0, -1.0),
        vec2( 1.0, -1.0),
        vec2( 1.0,  1.0),
        vec2(-1.0, -1.0),
        vec2( 1.0,  1.0),
        vec2(-1.0,  1.0)
    );
    vec2 uvs[6] = vec2[](
        vec2(0.0, 1.0),
        vec2(1.0, 1.0),
        vec2(1.0, 0.0),
        vec2(0.0, 1.0),
        vec2(1.0, 0.0),
        vec2(0.0, 0.0)
    );
    gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);
    out_uv = uvs[gl_VertexIndex];
}
'@

$fs2DSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

layout(binding = 0) uniform sampler2D pictureTexture;
layout(location=0) in vec2 in_uv;
layout(location=0) out vec4 out_color;

void main()
{
    vec4 texel = texture(pictureTexture, in_uv);
#if COLOR_SPACE == 0
    vec3 color = texel.rgb * texel.rgb;
#else
    vec3 color = texel.rgb;
#endif
    out_color = vec4(color, texel.a * layer.mOpacity);
}
'@

$vs2DPath = Join-Path $workDir "shader_pi2D_vk.vert"
$fs2DPath = Join-Path $workDir "shader_pi2D_vk.frag"
Set-Content -Path $vs2DPath -Value $vs2DSource -NoNewline -Encoding ASCII
Set-Content -Path $fs2DPath -Value $fs2DSource -NoNewline -Encoding ASCII

$vsVariants = New-Object System.Collections.Generic.List[string]
$fsVariants = New-Object System.Collections.Generic.List[string]
$vs2DVariants = New-Object System.Collections.Generic.List[string]
$fs2DVariants = New-Object System.Collections.Generic.List[string]

$vsOut = Join-Path $workDir "shader_pip360Equirect_vs_vk.spv"
& $glslang -V -S vert -o $vsOut $vsPath | Out-Host
if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $vsOut" }
& $spirvVal $vsOut
if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $vsOut" }
$vsVariants.Add($vsOut)

for ($colorSpace = 0; $colorSpace -le 1; ++$colorSpace) {
    $fsOut = Join-Path $workDir "shader_pip360Equirect_fs_vk_c${colorSpace}.spv"
    & $glslang -V -S frag "-DCOLOR_SPACE=$colorSpace" -o $fsOut $fsPath | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $fsOut" }
    & $spirvVal $fsOut
    if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $fsOut" }
    $fsVariants.Add($fsOut)
}

$vs2DOut = Join-Path $workDir "shader_pi2D_vs_vk.spv"
& $glslang -V -S vert -o $vs2DOut $vs2DPath | Out-Host
if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $vs2DOut" }
& $spirvVal $vs2DOut
if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $vs2DOut" }
$vs2DVariants.Add($vs2DOut)

for ($colorSpace = 0; $colorSpace -le 1; ++$colorSpace) {
    $fs2DOut = Join-Path $workDir "shader_pi2D_fs_vk_c${colorSpace}.spv"
    & $glslang -V -S frag "-DCOLOR_SPACE=$colorSpace" -o $fs2DOut $fs2DPath | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $fs2DOut" }
    & $spirvVal $fs2DOut
    if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $fs2DOut" }
    $fs2DVariants.Add($fs2DOut)
}

Write-SpvInclude (Join-Path $OutputDir "shader_pip360Equirect_vs_spirv.inc") "shader_pip360Equirect_vs_spirv" $vsVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pip360Equirect_fs_spirv.inc") "shader_pip360Equirect_fs_spirv" $fsVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pi2D_vs_spirv.inc") "shader_pi2D_vs_spirv" $vs2DVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pi2D_fs_spirv.inc") "shader_pi2D_fs_spirv" $fs2DVariants
