param(
    [string]$OutputDir = (Join-Path $PSScriptRoot "tmp")
)

$ErrorActionPreference = "Stop"

function Resolve-Tool([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK "Bin\$Name.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    $scoopCandidate = Join-Path $env:USERPROFILE "scoop\apps\vulkan\current\Bin\$Name.exe"
    if (Test-Path $scoopCandidate) {
        return $scoopCandidate
    }
    throw "$Name was not found on PATH, VULKAN_SDK, or the Scoop Vulkan SDK install path"
}

function Write-SpvInclude([string]$Path, [string]$Prefix, [array]$Variants) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// Generated by generate_vulkan_picture_shaders.ps1")
    $lines.Add("")
    for ($i = 0; $i -lt $Variants.Count; ++$i) {
        $bytes = [System.IO.File]::ReadAllBytes($Variants[$i])
        $lines.Add("static const unsigned int $($Prefix)$i[$($bytes.Length / 4)] = {")
        $words = New-Object System.Collections.Generic.List[string]
        for ($j = 0; $j -lt $bytes.Length; $j += 4) {
            $word = [BitConverter]::ToUInt32($bytes, $j)
            $words.Add(("0x{0:x8}u" -f $word))
        }
        for ($j = 0; $j -lt $words.Count; $j += 8) {
            $take = [Math]::Min(8, $words.Count - $j)
            $lines.Add("    " + (($words.GetRange($j, $take)) -join ", ") + ",")
        }
        $lines.Add("};")
        $lines.Add("")
    }
    $lines.Add("static const unsigned int *${Prefix}_code[$($Variants.Count)] = {")
    $lines.Add("    " + ((0..($Variants.Count - 1) | ForEach-Object { "$Prefix$_" }) -join ", "))
    $lines.Add("};")
    $lines.Add("static const int ${Prefix}_size[$($Variants.Count)] = {")
    $lines.Add("    " + (($Variants | ForEach-Object { [System.IO.File]::ReadAllBytes($_).Length }) -join ", "))
    $lines.Add("};")
    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding ASCII
}

$glslang = Resolve-Tool "glslangValidator"
$spirvVal = Resolve-Tool "spirv-val"

New-Item -ItemType Directory -Force $OutputDir | Out-Null
$workDir = Join-Path $OutputDir "vulkan_picture_spirv_work"
New-Item -ItemType Directory -Force $workDir | Out-Null

$vsSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

struct DisplayEye { mat4x4 mMatrix_CamPrj; };
layout (std140, row_major, binding=4) uniform DisplayState
{
    DisplayEye mEye[2];
    vec2       mResolution;
} display;

layout(location=0) in vec3 in_position;
layout(location=1) in vec3 in_normal;
layout(location=0) out vec3 out_direction;

void main()
{
    vec3 viewer_position = (layer.mLayerToViewer * vec4(in_position, 1.0)).xyz;
    out_direction = normalize(in_position);
    gl_Position = display.mEye[0].mMatrix_CamPrj * vec4(viewer_position, 1.0);
}
'@

$fsSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

layout(binding = 0) uniform sampler2D pictureTexture;
layout(location=0) in vec3 in_direction;
layout(location=0) out vec4 out_color;

const float k_pi = 3.1415927;

void main()
{
    vec3 nor = normalize(in_direction);
    vec2 uv = vec2(0.5 + 0.5 * atan(nor.x, -nor.z) / k_pi, acos(clamp(nor.y, -1.0, 1.0)) / k_pi);
    vec4 texel = texture(pictureTexture, uv);
    vec3 linearColor = pow(texel.rgb, vec3(2.2));
    float alpha = min(texel.a * layer.mOpacity, 0.65);
    out_color = vec4(linearColor, alpha);
}
'@

$vsPath = Join-Path $workDir "shader_pip360Equirect_vk.vert"
$fsPath = Join-Path $workDir "shader_pip360Equirect_vk.frag"
Set-Content -Path $vsPath -Value $vsSource -NoNewline -Encoding ASCII
Set-Content -Path $fsPath -Value $fsSource -NoNewline -Encoding ASCII

$vsVariants = New-Object System.Collections.Generic.List[string]
$fsVariants = New-Object System.Collections.Generic.List[string]

$vsOut = Join-Path $workDir "shader_pip360Equirect_vs_vk.spv"
& $glslang -V -S vert -o $vsOut $vsPath | Out-Host
if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $vsOut" }
& $spirvVal $vsOut
if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $vsOut" }
$vsVariants.Add($vsOut)

$fsOut = Join-Path $workDir "shader_pip360Equirect_fs_vk.spv"
& $glslang -V -S frag -o $fsOut $fsPath | Out-Host
if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $fsOut" }
& $spirvVal $fsOut
if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $fsOut" }
$fsVariants.Add($fsOut)

Write-SpvInclude (Join-Path $OutputDir "shader_pip360Equirect_vs_spirv.inc") "shader_pip360Equirect_vs_spirv" $vsVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pip360Equirect_fs_spirv.inc") "shader_pip360Equirect_fs_spirv" $fsVariants
