param(
    [string]$OutputDir = (Join-Path $PSScriptRoot "tmp")
)

$ErrorActionPreference = "Stop"

function Resolve-Tool([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK "Bin\$Name.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    $scoopCandidate = Join-Path $env:USERPROFILE "scoop\apps\vulkan\current\Bin\$Name.exe"
    if (Test-Path $scoopCandidate) {
        return $scoopCandidate
    }
    throw "$Name was not found on PATH, VULKAN_SDK, or the Scoop Vulkan SDK install path"
}

function Extract-GlslString([string]$Path) {
    $text = Get-Content $Path -Raw
    $start = $text.IndexOf('R"(')
    $end = $text.LastIndexOf(')";')
    if ($start -lt 0 -or $end -lt 0) {
        throw "Could not extract GLSL raw string from $Path"
    }
    return $text.Substring($start + 3, $end - ($start + 3))
}

function Convert-VertexGlslForVulkan([string]$Source) {
    $source = [regex]::Replace(
        $Source,
        '(?s)layout \(std140, row_major, binding=4\) uniform DisplayState\s*\{.*?\}display;',
        'layout (std140, row_major, binding=4) uniform DisplayState { DisplayEye mEye[2]; vec2 mResolution; } display;')
    $source = [regex]::Replace(
        $source,
        '(?s)layout \(std140, row_major, binding=9\) uniform ChunkData\s*\{.*?\}chunk_data;',
        'layout (std140, row_major, binding=9) uniform ChunkData { ChunkDataEntry mData[128]; } chunk_data;')
    $source = $source.Replace('uint bid = uint(real_vertexID);', 'uint bid = uint(gl_VertexID);')
    $source = [regex]::Replace(
        $source,
        '(?s)// this maps the first pt \(tim=0\).*?//vg\.col_tra \*= smoothstep\(layer\.mAnimParams\.z, layer\.mAnimParams\.z \+ layer\.mAnimParams\.w, drawingT\);\s*',
        "float drawingT = 2.0*layer.mDrawInTime-inTime;`n        vg.col_tra.w *= smoothstep(layer.mAnimParams.z, layer.mAnimParams.z + layer.mAnimParams.w, drawingT);`n    ")
    $source = $source.Replace('out V2CData', 'layout(location = 0) out V2CData')
    $source = $source.Replace('gl_VertexID', 'gl_VertexIndex')
    $source = $source.Replace('gl_InstanceID', 'gl_InstanceIndex')
    return "#version 460`nstruct DisplayEye { mat4x4 mMatrix_CamPrj; };`nstruct ChunkDataEntry { uint mVertexOffset; float mBiggestStroke; };`n$source"
}

function Convert-FragmentGlslForVulkan([string]$Source) {
    $source = [regex]::Replace($Source, '(?s)#extension GL_ARB_bindless_texture : enable\s*', '')
    $source = [regex]::Replace(
        $source,
        '(?s)layout\(binding = 7\) uniform GlobalResources\s*\{\s*uvec2 mTexBlueNoise;\s*\}globalResources;',
        'layout(binding = 7) uniform sampler2DArray globalBlueNoise;')
    $source = $source.Replace(
        'texelFetch( sampler2DArray(globalResources.mTexBlueNoise), ivec3(p,frameID)&63, 0 ).x',
        'texelFetch(globalBlueNoise, ivec3(p, int(frameID) & 63), 0).x')
    $source = $source.Replace('in vec4 mpos;', 'layout(location = 2) in vec4 mpos;')
    $source = $source.Replace('in V2CData', 'layout(location = 0) in V2CData')
    $source = $source.Replace(
        "#ifdef GL_OES_sample_variables`n    gl_SampleMask[0] = alpha2coverage( al, ivec2(gl_FragCoord.xy), frame.mFrame, vf.mask );`n    #endif",
        "gl_SampleMask[0] = alpha2coverage( al, ivec2(gl_FragCoord.xy), uint(frame.mFrame), vf.mask );")
    return "#version 460`n$source"
}

function Write-SpvInclude([string]$Path, [string]$Prefix, [array]$Variants) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// Generated by generate_vulkan_static_brush_shaders.ps1")
    $lines.Add("")
    for ($i = 0; $i -lt $Variants.Count; ++$i) {
        $bytes = [System.IO.File]::ReadAllBytes($Variants[$i])
        $lines.Add("static const unsigned int $($Prefix)$i[$($bytes.Length / 4)] = {")
        $words = New-Object System.Collections.Generic.List[string]
        for ($j = 0; $j -lt $bytes.Length; $j += 4) {
            $word = [BitConverter]::ToUInt32($bytes, $j)
            $words.Add(("0x{0:x8}u" -f $word))
        }
        for ($j = 0; $j -lt $words.Count; $j += 8) {
            $take = [Math]::Min(8, $words.Count - $j)
            $lines.Add("    " + (($words.GetRange($j, $take)) -join ", ") + ",")
        }
        $lines.Add("};")
        $lines.Add("")
    }
    $lines.Add("static const unsigned int *${Prefix}_code[$($Variants.Count)] = {")
    $lines.Add("    " + ((0..($Variants.Count - 1) | ForEach-Object { "$Prefix$_" }) -join ", "))
    $lines.Add("};")
    $lines.Add("static const int ${Prefix}_size[$($Variants.Count)] = {")
    $lines.Add("    " + (($Variants | ForEach-Object { [System.IO.File]::ReadAllBytes($_).Length }) -join ", "))
    $lines.Add("};")
    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding ASCII
}

$glslang = Resolve-Tool "glslangValidator"
$spirvVal = Resolve-Tool "spirv-val"

New-Item -ItemType Directory -Force $OutputDir | Out-Null
$workDir = Join-Path $OutputDir "vulkan_spirv_work"
New-Item -ItemType Directory -Force $workDir | Out-Null

$vsSource = Convert-VertexGlslForVulkan (Extract-GlslString (Join-Path $PSScriptRoot "shader_static_brush_vs.glsl"))
$fsSource = Convert-FragmentGlslForVulkan (Extract-GlslString (Join-Path $PSScriptRoot "shader_static_brush_fs.glsl"))
$vsPath = Join-Path $workDir "shader_static_brush_vk.vert"
$fsPath = Join-Path $workDir "shader_static_brush_vk.frag"
Set-Content -Path $vsPath -Value $vsSource -NoNewline -Encoding ASCII
Set-Content -Path $fsPath -Value $fsSource -NoNewline -Encoding ASCII

$vsVariants = New-Object System.Collections.Generic.List[string]
for ($colorCompressed = 0; $colorCompressed -le 1; ++$colorCompressed) {
    for ($brush = 0; $brush -lt 5; ++$brush) {
        for ($wiggle = 0; $wiggle -lt 2; ++$wiggle) {
            for ($drawin = 0; $drawin -lt 2; ++$drawin) {
                for ($stereo = 0; $stereo -lt 3; ++$stereo) {
                    $out = Join-Path $workDir "shader_static_brush_vs_c${colorCompressed}_b${brush}_w${wiggle}_d${drawin}_s${stereo}.spv"
                    & $glslang -V -S vert "-DCOLOR_COMPRESSED=$colorCompressed" "-DBRUSHTYPE=$brush" "-DWIGGLE=$wiggle" "-DDRAWIN=$drawin" "-DSTEREOMODE=$stereo" "-DVERTEX_FORMAT=0" -o $out $vsPath | Out-Host
                    if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $out" }
                    & $spirvVal $out
                    if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $out" }
                    $vsVariants.Add($out)
                }
            }
        }
    }
}

$fsVariants = New-Object System.Collections.Generic.List[string]
for ($stereo = 0; $stereo -lt 3; ++$stereo) {
    $out = Join-Path $workDir "shader_static_brush_fs_s${stereo}.spv"
    & $glslang -V -S frag "-DSTEREOMODE=$stereo" "-DRENDERMODE=0" -o $out $fsPath | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $out" }
    & $spirvVal $out
    if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $out" }
    $fsVariants.Add($out)
}

Write-SpvInclude (Join-Path $OutputDir "shader_static_brush_vs_spirv.inc") "shader_static_brush_vs_spirv" $vsVariants
Write-SpvInclude (Join-Path $OutputDir "shader_static_brush_fs_spirv.inc") "shader_static_brush_fs_spirv" $fsVariants
