param([string]$OutputDir = (Join-Path $PSScriptRoot "tmp"))
$ErrorActionPreference = "Stop"

function Resolve-Tool([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK "Bin\$Name.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    $scoopCandidate = Join-Path $env:USERPROFILE "scoop\apps\vulkan\current\Bin\$Name.exe"
    if (Test-Path $scoopCandidate) {
        return $scoopCandidate
    }
    throw "$Name was not found on PATH, VULKAN_SDK, or the Scoop Vulkan SDK install path"
}

function Extract-GlslString([string]$Path) {
    $text = Get-Content $Path -Raw
    $start = $text.IndexOf('R"(')
    $end = $text.LastIndexOf(')";')
    if ($start -lt 0 -or $end -lt 0) {
        throw "Could not extract GLSL raw string from $Path"
    }
    return $text.Substring($start + 3, $end - ($start + 3)).Replace("`r", "")
}

function Write-SpvInclude([string]$Path, [string]$Prefix, [array]$Variants) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// Generated by generate_vulkan_pretessellated_shaders.ps1")
    $lines.Add("")
    for ($i = 0; $i -lt $Variants.Count; ++$i) {
        $bytes = [System.IO.File]::ReadAllBytes($Variants[$i])
        $lines.Add("static const unsigned int $($Prefix)$i[$($bytes.Length / 4)] = {")
        $words = New-Object System.Collections.Generic.List[string]
        for ($j = 0; $j -lt $bytes.Length; $j += 4) {
            $word = [BitConverter]::ToUInt32($bytes, $j)
            $words.Add(("0x{0:x8}u" -f $word))
        }
        for ($j = 0; $j -lt $words.Count; $j += 8) {
            $take = [Math]::Min(8, $words.Count - $j)
            $lines.Add("    " + (($words.GetRange($j, $take)) -join ", ") + ",")
        }
        $lines.Add("};")
        $lines.Add("")
    }
    $lines.Add("static const unsigned int *${Prefix}_code[$($Variants.Count)] = {")
    $lines.Add("    " + ((0..($Variants.Count - 1) | ForEach-Object { "$Prefix$_" }) -join ", "))
    $lines.Add("};")
    $lines.Add("static const int ${Prefix}_size[$($Variants.Count)] = {")
    $lines.Add("    " + (($Variants | ForEach-Object { [System.IO.File]::ReadAllBytes($_).Length }) -join ", "))
    $lines.Add("};")
    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding ASCII
}


$glslang = Resolve-Tool "glslangValidator"
$spirvVal = Resolve-Tool "spirv-val"
$work = Join-Path $OutputDir "vulkan_spirv_pretessellated_work"
New-Item -ItemType Directory -Force $work | Out-Null
$vs = Extract-GlslString (Join-Path $PSScriptRoot "shader_pretessellated_brush_vs.glsl")
$vs = $vs.Replace('GL_ARB_shader_viewport_layer_array : enable', 'GL_EXT_multiview : require')
$vs = $vs.Replace('out V2CData', 'layout(location=0) out V2CData')
$vs = $vs.Replace('gl_InstanceID', 'gl_ViewIndex').Replace('    gl_ViewportIndex = gl_ViewIndex;', '')
# Vulkan integer attributes preserve the packed direction; decode as the HLSL route does.
$vs = $vs.Replace('in vec3  inOri;', 'in uvec4 inOri;')
$vs = $vs.Replace('layout (location=3) in uint  inInfo;', '#define inInfo inOri.w')
# The existing draw-in body is inactive; both 20/24-byte formats omit an unused time input.
$vs = $vs.Replace('layout (location=4) in float inTime;', '')
$vs = $vs.Replace('vec3 ori = inOri;', 'vec3 ori = normalize(-1.0 + 2.0 * vec3(inOri.xyz) / 255.0);')
$fs = Extract-GlslString (Join-Path $PSScriptRoot "shader_pretessellated_brush_fs.glsl")
$fs = $fs.Replace('in vec4 mpos;', '').Replace('in V2CData', 'layout(location=0) in V2CData')
$fs = $fs.Replace('ivec3(p,frameID)&63', 'ivec3(p, int(frameID) & 63)')
$fs = $fs.Replace('frame.mFrame, vf.mask', 'uint(frame.mFrame), vf.mask')
$fs = $fs.Replace("#ifdef GL_OES_sample_variables`n`t", "#if 1`n`t")
$vsPath = Join-Path $work "pretessellated.vert"
$fsPath = Join-Path $work "pretessellated.frag"
Set-Content $vsPath "#version 450`n$vs" -Encoding ASCII
Set-Content $fsPath "#version 450`n$fs" -Encoding ASCII
$vertices = @()
for ($color = 0; $color -lt 2; ++$color) {
for ($wiggle = 0; $wiggle -lt 2; ++$wiggle) {
for ($drawin = 0; $drawin -lt 2; ++$drawin) {
for ($stereo = 0; $stereo -lt 3; ++$stereo) {
    $index = $stereo + 3 * $drawin + 6 * $wiggle + 12 * $color
    $out = Join-Path $work "pretessellated-vs-$index.spv"
    & $glslang -V -S vert "-DSTEREOMODE=$stereo" "-DWIGGLE=$wiggle" "-DDRAWIN=$drawin" "-DCOLOR_COMPRESSED=$color" -o $out $vsPath | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Pretessellated vertex shader $index failed" }
    & $spirvVal $out
    if ($LASTEXITCODE -ne 0) { throw "Pretessellated vertex SPIR-V $index is invalid" }
    $vertices += $out
}}}}
$out = Join-Path $work "pretessellated-fs.spv"
& $glslang -V -S frag -DRENDERMODE=0 -o $out $fsPath | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Pretessellated fragment shader failed" }
& $spirvVal $out
if ($LASTEXITCODE -ne 0) { throw "Pretessellated fragment SPIR-V is invalid" }
Write-SpvInclude (Join-Path $OutputDir "shader_pretessellated_brush_vs_spirv.inc") "shader_pretessellated_brush_vs_spirv" $vertices
Write-SpvInclude (Join-Path $OutputDir "shader_pretessellated_brush_fs_spirv.inc") "shader_pretessellated_brush_fs_spirv" @($out)
