param([string]$OutputDir = (Join-Path $PSScriptRoot "tmp"))
$ErrorActionPreference = "Stop"

function Resolve-Tool([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK "Bin\$Name.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    $scoopCandidate = Join-Path $env:USERPROFILE "scoop\apps\vulkan\current\Bin\$Name.exe"
    if (Test-Path $scoopCandidate) {
        return $scoopCandidate
    }
    throw "$Name was not found on PATH, VULKAN_SDK, or the Scoop Vulkan SDK install path"
}

function Extract-GlslString([string]$Path) {
    $text = Get-Content $Path -Raw
    $start = $text.IndexOf('R"(')
    $end = $text.LastIndexOf(')";')
    if ($start -lt 0 -or $end -lt 0) {
        throw "Could not extract GLSL raw string from $Path"
    }
    return $text.Substring($start + 3, $end - ($start + 3)).Replace("`r", "")
}

function Write-SpvInclude([string]$Path, [string]$Prefix, [array]$Variants) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// Generated by generate_vulkan_model_shaders.ps1")
    $lines.Add("")
    for ($i = 0; $i -lt $Variants.Count; ++$i) {
        $bytes = [System.IO.File]::ReadAllBytes($Variants[$i])
        $lines.Add("static const unsigned int $($Prefix)$i[$($bytes.Length / 4)] = {")
        $words = New-Object System.Collections.Generic.List[string]
        for ($j = 0; $j -lt $bytes.Length; $j += 4) {
            $word = [BitConverter]::ToUInt32($bytes, $j)
            $words.Add(("0x{0:x8}u" -f $word))
        }
        for ($j = 0; $j -lt $words.Count; $j += 8) {
            $take = [Math]::Min(8, $words.Count - $j)
            $lines.Add("    " + (($words.GetRange($j, $take)) -join ", ") + ",")
        }
        $lines.Add("};")
        $lines.Add("")
    }
    $lines.Add("static const unsigned int *${Prefix}_code[$($Variants.Count)] = {")
    $lines.Add("    " + ((0..($Variants.Count - 1) | ForEach-Object { "$Prefix$_" }) -join ", "))
    $lines.Add("};")
    $lines.Add("static const int ${Prefix}_size[$($Variants.Count)] = {")
    $lines.Add("    " + (($Variants | ForEach-Object { [System.IO.File]::ReadAllBytes($_).Length }) -join ", "))
    $lines.Add("};")
    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding ASCII
}


$glslang = Resolve-Tool "glslangValidator"
$spirvVal = Resolve-Tool "spirv-val"
$work = Join-Path $OutputDir "vulkan_spirv_model_work"
New-Item -ItemType Directory -Force $work | Out-Null
$vs = Extract-GlslString (Join-Path $PSScriptRoot "shader_model_vs.glsl")
$vs = $vs.Replace('GL_ARB_shader_viewport_layer_array : enable', 'GL_EXT_multiview : require')
$vs = $vs.Replace('out V2FData', 'layout(location=0) out V2FData')
$vs = $vs.Replace('gl_InstanceID', 'gl_ViewIndex')
$vs = $vs.Replace('    gl_ViewportIndex = gl_ViewIndex;', '')
$fs = Extract-GlslString (Join-Path $PSScriptRoot "shader_model_fs.glsl")
$fs = $fs.Replace('layout (binding=0) uniform sampler2D unTex0;', '')
$fs = $fs.Replace('in V2FData', 'layout(location=0) in V2FData')
$fs = $fs.Replace('out vec4 outColor;', 'layout(location=0) out vec4 outColor;')
# Model vertex colours are stored in gamma space, matching the HLSL route.
$fs = $fs.Replace('vec3 col = vf.Col;', "vec3 col = vf.Col;`n#if COLOR_SPACE==0`n    col = pow(abs(col), vec3(2.2));`n#endif")
$fs = $fs.Replace('ivec3(p,frameID)&63', 'ivec3(p, int(frameID) & 63)')
$fs = $fs.Replace('frame.mFrame, 0);', 'uint(frame.mFrame), 0);')
# Vulkan GLSL exposes sample-mask outputs directly, without the GLES extension.
$fs = $fs.Replace("#ifdef GL_OES_sample_variables`n`tgl_SampleMask", "#if 1`n`tgl_SampleMask")
$vsPath = Join-Path $work "model.vert"
$fsPath = Join-Path $work "model.frag"
Set-Content $vsPath "#version 450`n$vs" -Encoding ASCII
Set-Content $fsPath "#version 450`n$fs" -Encoding ASCII
$vertices = @()
for ($stereo = 0; $stereo -lt 3; ++$stereo) {
    $out = Join-Path $work "model-vs-$stereo.spv"
    & $glslang -V -S vert "-DSTEREOMODE=$stereo" -o $out $vsPath | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Model vertex shader $stereo failed" }
    & $spirvVal $out
    if ($LASTEXITCODE -ne 0) { throw "Model vertex SPIR-V $stereo is invalid" }
    $vertices += $out
}
$fragments = @()
for ($color = 0; $color -lt 2; ++$color) {
    $out = Join-Path $work "model-fs-$color.spv"
    & $glslang -V -S frag "-DCOLOR_SPACE=$color" -o $out $fsPath | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Model fragment shader $color failed" }
    & $spirvVal $out
    if ($LASTEXITCODE -ne 0) { throw "Model fragment SPIR-V $color is invalid" }
    $fragments += $out
}
Write-SpvInclude (Join-Path $OutputDir "shader_model_vs_spirv.inc") "shader_model_vs_spirv" $vertices
Write-SpvInclude (Join-Path $OutputDir "shader_model_fs_spirv.inc") "shader_model_fs_spirv" $fragments
