plugins {
    id 'com.android.library'
}

android {
    namespace 'org.linuxfoundation.imm.stroke_reader'
    compileSdk 34
    ndkVersion "26.1.10909125"

    defaultConfig {
        minSdk 26
        targetSdk 34

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17", "-DANDROID", "-Werror"
                arguments "-DANDROID_STL=c++_shared",
                        "-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY",
                        "-DCMAKE_C_COMPILER_WORKS=1",
                        "-DCMAKE_CXX_COMPILER_WORKS=1",
                        "-DCMAKE_C_ABI_COMPILED=1",
                        "-DCMAKE_CXX_ABI_COMPILED=1"
                abiFilters "arm64-v8a"
                targets "ImmStrokeReader"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            jniLibs.srcDir 'libs'
        }
    }
}
