<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <IMM_OGGIncDir>..\..\thirdparty\libogg\include;..\..\thirdparty\libvorbis\include;</IMM_OGGIncDir>
    <IMM_OGGLibDir>..\..\thirdparty\libogg\lib</IMM_OGGLibDir>
    <IMM_VorbisLibDir>..\..\thirdparty\libvorbis\lib</IMM_VorbisLibDir>
  </PropertyGroup>
</Project>