---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI Validation Matrix

on:
  workflow_dispatch:
  schedule:
    - cron: '17 2 * * *'
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled]

jobs:
  core:
    name: Core
    uses: ./.github/workflows/ci-core.yml
    secrets: inherit

  device:
    name: Device
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || contains(github.event.head_commit.message, '[CI VALIDATION]')
    uses: ./.github/workflows/ci-device.yml
    secrets: inherit

  engine:
    name: Engine
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || contains(github.event.head_commit.message, '[CI VALIDATION]')
    uses: ./.github/workflows/ci-engine.yml
    secrets: inherit

  gpu:
    name: GPU
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || contains(github.event.head_commit.message, '[CI VALIDATION]')
    uses: ./.github/workflows/ci-gpu.yml
    secrets: inherit
